language: php

php:
  - 7.0
  - 7.1

matrix:
  fast_finish: true

cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - composer install --prefer-dist

script:
  - mkdir -p build/logs
  - composer test
  - composer style

after_script:
  - composer coverage
